name: Build to .jar file

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate .jar
        run: |
          rm Chocolate-assembly-*.jar || true
          sbt assembly
          cd target
          cd $(ls | grep scala-)
          mv $(ls | grep Chocolate-assembly-) ../..
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate .jar file"
