name: Generate JS files

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate JS files
        run: |
          sbt chocolateJS/fullOptJS
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate JS files"
