name: Build to .jar file and generate JS files

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  generate-jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate .jar
        run: |
          rm Chocolate.jar || true
          sbt assembly
          cd jvm/target
          cd $(ls | grep scala-3 | head -n 1)
          mv Chocolate.jar ../../..
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate .jar file"
  generate-js:
    runs-on: ubuntu-latest
    needs: generate-jar

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate JS files
        run: |
          sbt chocolateJS/fullOptJS
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate JS files"
